# Generated by Django 4.1.7 on 2024-06-21 14:46

from django.db import migrations, models
import oj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email_id', models.CharField(default='', max_length=64, unique=True)),
                ('username', models.CharField(default=oj.models.generate_unique_username, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(default=oj.models.generates_unique_password, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
