# Generated by Django 4.1.7 on 2024-06-26 14:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Problem_id', models.CharField(default=api.models.generates_unique_password, max_length=64, unique=True)),
                ('statement', models.CharField(default='', max_length=16, unique=True)),
                ('level', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('D', 'Difficult'), ('T', 'Tricky')], default='E', max_length=16)),
                ('solution', models.CharField(default='', max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email_id', models.CharField(default='', max_length=64, unique=True)),
                ('username', models.CharField(default=api.models.generate_unique_username, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(default=api.models.generates_unique_password, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
